name: ChatEdit
version: 1.0
author: Scott
description: Allows the user to view chat globally, nearby, not at all or in other predefined chat types.
main: me.scotth0828.ChatEdit.Main.Main
commands:
  ChatType:
    description: Sets what type of chat you'd like to use from the current chat types available.
    usage: /<command> <value>
    aliases: [ct]
  ChatR:
    description: Sets the radius for when chat is set to nearby. The default is set to 200.
    usage: /<command> <value>
    aliases: [cr]
  ChatF:
    description: Forces the specified player's chat type.
    usage: /<command> <player> <value>
    aliases: [cf]
    permission: ChatEdit.forceType
  ChatAdmin:
    description: Allows the user to see all chat types.
    usage: /<command>
    aliases: [ca]
    permission: ChatEdit.ChatAdmin
  ChatL:
    description: Lists current chat types available.
    usage: /<command>
    aliases: [cl]
  ChatEditReload:
    description: Reloads the plugin configuration and user data.
    usage: /<command>
    permission: ChatEdit.reload